// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channelImform.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "ChannelImform.pbobjc.h"
#import "ChannelBase.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ChannelImformRoot

@implementation ChannelImformRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - ChannelImformRoot_FileDescriptor

static GPBFileDescriptor *ChannelImformRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"uyujoy.com.api.channel.frontend"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - channelStateChange

@implementation channelStateChange

@dynamic hasCh, ch;
@dynamic reason;

typedef struct channelStateChange__storage_ {
  uint32_t _has_storage_[1];
  uint32_t reason;
  channel *ch;
} channelStateChange__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "ch",
        .dataTypeSpecific.className = GPBStringifySymbol(channel),
        .number = channelStateChange_FieldNumber_Ch,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(channelStateChange__storage_, ch),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "reason",
        .dataTypeSpecific.className = NULL,
        .number = channelStateChange_FieldNumber_Reason,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(channelStateChange__storage_, reason),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[channelStateChange class]
                                     rootClass:[ChannelImformRoot class]
                                          file:ChannelImformRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(channelStateChange__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - channelUserStateChange

@implementation channelUserStateChange

@dynamic hasChu, chu;
@dynamic reason;

typedef struct channelUserStateChange__storage_ {
  uint32_t _has_storage_[1];
  uint32_t reason;
  channelUser *chu;
} channelUserStateChange__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "chu",
        .dataTypeSpecific.className = GPBStringifySymbol(channelUser),
        .number = channelUserStateChange_FieldNumber_Chu,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(channelUserStateChange__storage_, chu),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "reason",
        .dataTypeSpecific.className = NULL,
        .number = channelUserStateChange_FieldNumber_Reason,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(channelUserStateChange__storage_, reason),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[channelUserStateChange class]
                                     rootClass:[ChannelImformRoot class]
                                          file:ChannelImformRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(channelUserStateChange__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
