// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channelIm.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class channelMsgRecord;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ChannelImRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ChannelImRoot : GPBRootObject
@end

#pragma mark - channelMsgRecord

typedef GPB_ENUM(channelMsgRecord_FieldNumber) {
  channelMsgRecord_FieldNumber_MsgId = 1,
  channelMsgRecord_FieldNumber_MsgFp = 2,
  channelMsgRecord_FieldNumber_From = 3,
  channelMsgRecord_FieldNumber_ChannelId = 4,
  channelMsgRecord_FieldNumber_Msg = 5,
  channelMsgRecord_FieldNumber_SendTime = 6,
  channelMsgRecord_FieldNumber_Lang = 7,
};

@interface channelMsgRecord : GPBMessage

/** 自增ID，但可能不连续，用于进行服务器-客户端同步 */
@property(nonatomic, readwrite) uint32_t msgId;

/** 消息唯一随机值，用于去重 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgFp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelId;

/** 文本消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite) int64_t sendTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lang;

@end

#pragma mark - channelMsgRecordAck

typedef GPB_ENUM(channelMsgRecordAck_FieldNumber) {
  channelMsgRecordAck_FieldNumber_MsgId = 1,
  channelMsgRecordAck_FieldNumber_Fp = 2,
};

@interface channelMsgRecordAck : GPBMessage

@property(nonatomic, readwrite) uint32_t msgId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fp;

@end

#pragma mark - rcvChannelMsgRecord

typedef GPB_ENUM(rcvChannelMsgRecord_FieldNumber) {
  rcvChannelMsgRecord_FieldNumber_Msg = 1,
};

@interface rcvChannelMsgRecord : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) channelMsgRecord *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - getDiffChannelMsgRecord

typedef GPB_ENUM(getDiffChannelMsgRecord_FieldNumber) {
  getDiffChannelMsgRecord_FieldNumber_MsgId = 1,
  getDiffChannelMsgRecord_FieldNumber_ChannelId = 2,
};

@interface getDiffChannelMsgRecord : GPBMessage

@property(nonatomic, readwrite) uint32_t msgId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelId;

@end

#pragma mark - getDiffChannelMsgRecordAck

typedef GPB_ENUM(getDiffChannelMsgRecordAck_FieldNumber) {
  getDiffChannelMsgRecordAck_FieldNumber_ListArray = 1,
};

@interface getDiffChannelMsgRecordAck : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<channelMsgRecord*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
