// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channelImform.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class channel;
@class channelUser;
@class matchAttr;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ChannelImformRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ChannelImformRoot : GPBRootObject
@end

#pragma mark - channelStateChange

typedef GPB_ENUM(channelStateChange_FieldNumber) {
  channelStateChange_FieldNumber_Ch = 1,
  channelStateChange_FieldNumber_Reason = 2,
};

@interface channelStateChange : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) channel *ch;
/** Test to see if @c ch has been set. */
@property(nonatomic, readwrite) BOOL hasCh;

@property(nonatomic, readwrite) uint32_t reason;

@end

#pragma mark - channelUserStateChange

typedef GPB_ENUM(channelUserStateChange_FieldNumber) {
  channelUserStateChange_FieldNumber_Chu = 1,
  channelUserStateChange_FieldNumber_Reason = 2,
};

@interface channelUserStateChange : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) channelUser *chu;
/** Test to see if @c chu has been set. */
@property(nonatomic, readwrite) BOOL hasChu;

@property(nonatomic, readwrite) uint32_t reason;

@end

#pragma mark - channelMatched

typedef GPB_ENUM(channelMatched_FieldNumber) {
  channelMatched_FieldNumber_Ch = 1,
  channelMatched_FieldNumber_Token = 2,
  channelMatched_FieldNumber_SelfUniqId = 3,
  channelMatched_FieldNumber_PeerUniqId = 4,
  channelMatched_FieldNumber_MatchedUserAttr = 5,
  channelMatched_FieldNumber_Ts = 6,
};

/**
 * 匹配通知
 **/
@interface channelMatched : GPBMessage

/** 频道信息 */
@property(nonatomic, readwrite, strong, null_resettable) channel *ch;
/** Test to see if @c ch has been set. */
@property(nonatomic, readwrite) BOOL hasCh;

/** 频道token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** 进入频道时使用的唯一Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *selfUniqId;

/** 对方进入频道时使用的唯一Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *peerUniqId;

/** 对方的匹配熟悉 */
@property(nonatomic, readwrite, strong, null_resettable) matchAttr *matchedUserAttr;
/** Test to see if @c matchedUserAttr has been set. */
@property(nonatomic, readwrite) BOOL hasMatchedUserAttr;

/** 本次匹配对应的ts */
@property(nonatomic, readwrite) int64_t ts;

@end

#pragma mark - channelSkipped

typedef GPB_ENUM(channelSkipped_FieldNumber) {
  channelSkipped_FieldNumber_ChannelId = 1,
};

/**
 * 跳过通知
 **/
@interface channelSkipped : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelId;

@end

#pragma mark - matchAttr

typedef GPB_ENUM(matchAttr_FieldNumber) {
  matchAttr_FieldNumber_Name = 1,
  matchAttr_FieldNumber_PhotoURL = 2,
  matchAttr_FieldNumber_Gender = 3,
};

@interface matchAttr : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 头像URL */
@property(nonatomic, readwrite, copy, null_resettable) NSString *photoURL;

/** 1. 男 2.女 */
@property(nonatomic, readwrite) uint32_t gender;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
