// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http_error.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "HTTPError.pbobjc.h"
#import "Any.pbobjc.h"
#import "Code.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - HTTPErrorRoot

@implementation HTTPErrorRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - HTTPErrorRoot_FileDescriptor

static GPBFileDescriptor *HTTPErrorRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"uyujoy.api.http"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - WssError

@implementation WssError

@dynamic code;
@dynamic message;
@dynamic status;
@dynamic detailsArray, detailsArray_Count;

typedef struct WssError__storage_ {
  uint32_t _has_storage_[1];
  int32_t code;
  RPCCode status;
  NSString *message;
  NSMutableArray *detailsArray;
} WssError__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "code",
        .dataTypeSpecific.className = NULL,
        .number = WssError_FieldNumber_Code,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(WssError__storage_, code),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "message",
        .dataTypeSpecific.className = NULL,
        .number = WssError_FieldNumber_Message,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(WssError__storage_, message),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "status",
        .dataTypeSpecific.enumDescFunc = RPCCode_EnumDescriptor,
        .number = WssError_FieldNumber_Status,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(WssError__storage_, status),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "detailsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GPBAny),
        .number = WssError_FieldNumber_DetailsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(WssError__storage_, detailsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[WssError class]
                                     rootClass:[HTTPErrorRoot class]
                                          file:HTTPErrorRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(WssError__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t WssError_Status_RawValue(WssError *message) {
  GPBDescriptor *descriptor = [WssError descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:WssError_FieldNumber_Status];
  return GPBGetMessageInt32Field(message, field);
}

void SetWssError_Status_RawValue(WssError *message, int32_t value) {
  GPBDescriptor *descriptor = [WssError descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:WssError_FieldNumber_Status];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
