// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http_error.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBAny;
GPB_ENUM_FWD_DECLARE(RPCCode);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HTTPErrorRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HTTPErrorRoot : GPBRootObject
@end

#pragma mark - WssError

typedef GPB_ENUM(WssError_FieldNumber) {
  WssError_FieldNumber_Code = 1,
  WssError_FieldNumber_Message = 2,
  WssError_FieldNumber_Status = 4,
  WssError_FieldNumber_DetailsArray = 5,
};

/**
 * This message defines the error schema for Google's JSON HTTP APIs.
 **/
@interface WssError : GPBMessage

/** The HTTP status code that corresponds to `google.rpc.Status.code`. */
@property(nonatomic, readwrite) int32_t code;

/** This corresponds to `google.rpc.Status.message`. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** This is the enum version for `google.rpc.Status.code`. */
@property(nonatomic, readwrite) enum RPCCode status;

/** This corresponds to `google.rpc.Status.details`. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *detailsArray;
/** The number of items in @c detailsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger detailsArray_Count;

@end

/**
 * Fetches the raw value of a @c WssError's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t WssError_Status_RawValue(WssError *message);
/**
 * Sets the raw value of an @c WssError's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetWssError_Status_RawValue(WssError *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
